
          rm -r app_pojavlauncher/src/main/assets/components/jre
          rm -r app_pojavlauncher/src/main/assets/components/jre-new
          rm -r app_pojavlauncher/src/main/assets/components/jre-21
          gradle assembleDebug
          mv app_pojavlauncher/build/outputs/apk/debug/app_pojavlauncher-debug.apk out/app-debug-noruntime.apk
      - name: Gen md5sums
        run: |
          md5sum out/app-debug.apk > out/app-debug.md5
          md5sum out/app-debug-noruntime.apk > out/app-debug-noruntime.md5

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: out/app-debug.*

      - name: Upload AAB
        uses: actions/upload-artifact@v3
        with:
          name: app-release-aab
          path: out/app-gplay.aab

      - name: Upload onto the Google Play testing track
        continue-on-error: true
        if: github.repository_owner == 'PojavLauncherTeam' && github.ref_name == 'v3_openjdk'
        uses: r0adkll/upload-google-play@v1.1.2
        with:
          serviceAccountJsonPlainText: ${{ secrets.GPLAY_SERVICE_JSON }}
          packageName: net.kdt.pojavlaunch
          releaseFiles: out/app-gplay.aab
          track: internal
          inAppUpdatePriority: 5

      - name: Upload APK (without runtime)
        uses: actions/upload-artifact@v3
        with:
          name: app-debug-noruntime
          path: out/app-debug-noruntime.*
